# Generated by Django 5.0.2 on 2024-04-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_pricecoefficient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistancePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=500)),
                ('to_location', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('num_vehicles', models.IntegerField()),
            ],
        ),
    ]
