# Generated by Django 5.0.2 on 2024-04-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_trip_delete_distanceprice_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], max_length=20)),
                ('date', models.DateTimeField()),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('number_of_people', models.IntegerField()),
                ('number_of_cars', models.IntegerField()),
                ('distance', models.TextField()),
                ('price', models.TextField()),
            ],
        ),
    ]
