# Generated by Django 5.0.2 on 2024-04-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_tripson'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistancePriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('number_of_people', models.IntegerField()),
                ('number_of_cars', models.IntegerField()),
                ('distance', models.TextField()),
                ('price', models.TextField()),
            ],
        ),
    ]
