# Generated by Django 5.0.2 on 2024-04-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_alter_location_latitude_alter_location_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_url',
        ),
        migrations.AddField(
            model_name='car',
            name='chosen_count',
            field=models.IntegerField(default=0),
        ),
    ]
