# Generated by Django 5.0.2 on 2024-04-04 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0010_rename_model_name_car_name_remove_car_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('selection_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'car_id')},
            },
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AddField(
            model_name='tripson',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='tripson',
            name='phone',
            field=models.CharField(default='(+90)511-111-11-11', max_length=20),
        ),
        migrations.AddField(
            model_name='tripson',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
