# Generated by Django 5.0.2 on 2024-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_selectedcar_delete_car_tripson_email_tripson_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.AlterField(
            model_name='tripson',
            name='distance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripson',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tripson',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tripson',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripson',
            name='trip_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tripson',
            name='vehicle_id',
            field=models.CharField(max_length=100),
        ),
    ]
