# Generated by Django 5.0.2 on 2024-05-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0012_delete_trip_alter_tripson_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripson',
            name='vehicle_id',
            field=models.CharField(max_length=500),
        ),
    ]
