# Generated by Django 5.0.2 on 2024-05-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0013_alter_tripson_vehicle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], max_length=20)),
                ('date', models.DateTimeField()),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('number_of_people', models.IntegerField()),
                ('number_of_cars', models.IntegerField()),
                ('distance', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='tripson',
            name='distance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripson',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='tripson',
            name='phone',
            field=models.CharField(default='(+90)511-111-11-11', max_length=20),
        ),
        migrations.AlterField(
            model_name='tripson',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripson',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tripson',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
