# Generated by Django 5.0.2 on 2024-05-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0014_trip_alter_tripson_distance_alter_tripson_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripson',
            name='distance',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tripson',
            name='price',
            field=models.TextField(),
        ),
    ]
