# Generated by Django 5.0.2 on 2024-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0015_alter_tripson_distance_alter_tripson_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripson',
            name='destination',
            field=models.CharField(max_length=500),
        ),
    ]
