# Generated by Django 5.0.2 on 2024-05-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0017_alter_distancepricedata_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancepricedata',
            name='destination',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='distancepricedata',
            name='distance',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='distancepricedata',
            name='origin',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='distancepricedata',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tripson',
            name='origin',
            field=models.CharField(max_length=500),
        ),
    ]
